/*
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BadRequestResponseErrors
 */

public class BadRequestResponseErrors {
  @SerializedName("common")
  private List<String> common = null;

  @SerializedName("fields")
  private Object fields = null;

  public BadRequestResponseErrors common(List<String> common) {
    this.common = common;
    return this;
  }

  public BadRequestResponseErrors addCommonItem(String commonItem) {
    if (this.common == null) {
      this.common = new ArrayList<String>();
    }
    this.common.add(commonItem);
    return this;
  }

   /**
   * Get common
   * @return common
  **/
  @ApiModelProperty(example = "[\"Common error message 1\",\"Common error message 2\"]", value = "")
  public List<String> getCommon() {
    return common;
  }

  public void setCommon(List<String> common) {
    this.common = common;
  }

  public BadRequestResponseErrors fields(Object fields) {
    this.fields = fields;
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(example = "{\"fieldName1\":[\"Error message 1\",\"Error message 2\"],\"fieldName2\":[\"Error message 3\",\"Error message 4\"]}", value = "")
  public Object getFields() {
    return fields;
  }

  public void setFields(Object fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BadRequestResponseErrors badRequestResponseErrors = (BadRequestResponseErrors) o;
    return Objects.equals(this.common, badRequestResponseErrors.common) &&
        Objects.equals(this.fields, badRequestResponseErrors.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(common, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BadRequestResponseErrors {\n");
    
    sb.append("    common: ").append(toIndentedString(common)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

