/*
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BuyDedicatedNumberInputObject
 */

public class BuyDedicatedNumberInputObject {
  @SerializedName("phone")
  private String phone = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("userId")
  private Integer userId = null;

  public BuyDedicatedNumberInputObject phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Desired dedicated phone number in international E.164 format
   * @return phone
  **/
  @ApiModelProperty(example = "123456780", required = true, value = "Desired dedicated phone number in international E.164 format")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public BuyDedicatedNumberInputObject country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Dedicated number country. Two charactes in upper case.
   * @return country
  **/
  @ApiModelProperty(example = "AU", required = true, value = "Dedicated number country. Two charactes in upper case.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BuyDedicatedNumberInputObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * User ID this number will be assigned to
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "User ID this number will be assigned to")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyDedicatedNumberInputObject buyDedicatedNumberInputObject = (BuyDedicatedNumberInputObject) o;
    return Objects.equals(this.phone, buyDedicatedNumberInputObject.phone) &&
        Objects.equals(this.country, buyDedicatedNumberInputObject.country) &&
        Objects.equals(this.userId, buyDedicatedNumberInputObject.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, country, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyDedicatedNumberInputObject {\n");
    
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

