/*
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.Country;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * DoCarrierLookupResponse
 */

public class DoCarrierLookupResponse {
  @SerializedName("cost")
  private BigDecimal cost = null;

  @SerializedName("country")
  private Country country = null;

  @SerializedName("local")
  private String local = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("carrier")
  private String carrier = null;

  @SerializedName("number164")
  private String number164 = null;

  @SerializedName("valid")
  private Boolean valid = null;

  public DoCarrierLookupResponse cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  @ApiModelProperty(example = "0.04", required = true, value = "")
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  public DoCarrierLookupResponse country(Country country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }

  public DoCarrierLookupResponse local(String local) {
    this.local = local;
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  @ApiModelProperty(example = "(541) 754-3010", required = true, value = "")
  public String getLocal() {
    return local;
  }

  public void setLocal(String local) {
    this.local = local;
  }

  public DoCarrierLookupResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "mobile", required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DoCarrierLookupResponse carrier(String carrier) {
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @ApiModelProperty(example = "Example Messaging Systems", required = true, value = "")
  public String getCarrier() {
    return carrier;
  }

  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }

  public DoCarrierLookupResponse number164(String number164) {
    this.number164 = number164;
    return this;
  }

   /**
   * Get number164
   * @return number164
  **/
  @ApiModelProperty(example = "+15417543010", required = true, value = "")
  public String getNumber164() {
    return number164;
  }

  public void setNumber164(String number164) {
    this.number164 = number164;
  }

  public DoCarrierLookupResponse valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @ApiModelProperty(example = "true", required = true, value = "")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoCarrierLookupResponse doCarrierLookupResponse = (DoCarrierLookupResponse) o;
    return Objects.equals(this.cost, doCarrierLookupResponse.cost) &&
        Objects.equals(this.country, doCarrierLookupResponse.country) &&
        Objects.equals(this.local, doCarrierLookupResponse.local) &&
        Objects.equals(this.type, doCarrierLookupResponse.type) &&
        Objects.equals(this.carrier, doCarrierLookupResponse.carrier) &&
        Objects.equals(this.number164, doCarrierLookupResponse.number164) &&
        Objects.equals(this.valid, doCarrierLookupResponse.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cost, country, local, type, carrier, number164, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoCarrierLookupResponse {\n");
    
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    number164: ").append(toIndentedString(number164)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

